apiVersion: v1
kind: Service
metadata:
  name: "helloworld-svc"
spec:
  ports:
    - port: 8081
      targetPort: 8080
      name: http
  type: NodePort
  selector:
    app: "helloworld" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "helloworld-deploy"
spec:
  selector:
    matchLabels:
      app: "helloworld"
  replicas: 1
  template:
    metadata:
      labels:
        app: "helloworld"
    spec:
      containers:
      - image: "757992231822.dkr.ecr.eu-west-1.amazonaws.com/helloworld:$VERSION$"
        name: "helloworld"
        ports:
        - containerPort: 8080
